#! /bin/sh

# Monitors
bspc monitor HDMI-0 -d 1 3 5 7 9 
bspc monitor DP-1 -d 2 4 6 8 10

# Globals
bspc config automatic_scheme fibonacci
bspc config pointer_modifier mod
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Gaps

bspc config -m HDMI-0 top_padding 27
bspc config -m DP-1 top_padding 27
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width         2 
bspc config window_gap          10

# Source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
